// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeechRecognitionThesis.Models.Database;

namespace SpeechRecognitionThesis.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20191229212702_SpeechRecognitionThesis.Models.Database.RepositoryContext")]
    partial class SpeechRecognitionThesisModelsDatabaseRepositoryContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpeechRecognitionThesis.Models.Article", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ArticleCategoryRefId");

                    b.Property<string>("ArticleModificationDate")
                        .HasMaxLength(50);

                    b.Property<string>("Content")
                        .HasMaxLength(4000);

                    b.Property<long>("NumberOfViews");

                    b.Property<string>("Subject")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ArticleCategoryRefId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ArticleCategoryRefId = 2L,
                            ArticleModificationDate = "28.06.2019 11:20:58",
                            Content = "zwierzęta należące do kręgowców, charakteryzujące się głównie występowaniem gruczołów mlekowych u samic, zazwyczaj obecnością owłosienia oraz stałocieplnością. Około 60% ssaków utrzymuje temperaturę w granicach 34 a 39 stopni Celcjusza. Stałocieplność umożliwia aktywny tryb życia w różnych środowiskach. Od mroźnych obszarów podbiegunowych do gorących tropików. Futro i tłuszcz pomagają uchronić się przed zimnem, a wydzielanie potu i szybki oddech pomagają pozbyć się nadmiernego ciepła.",
                            NumberOfViews = 12L,
                            Subject = "Ssaki"
                        },
                        new
                        {
                            Id = 2L,
                            ArticleCategoryRefId = 1L,
                            ArticleModificationDate = "15.09.2019 14:32:21",
                            Content = "Polak na podium. Po dwóch kapitalnych skokach polskiego skoczka, zajął 3 miejsce w turnieju czterech skoczni.Zawody wygrał Japończyk Ryoyu Kobayashi. Możemy być dumni z naszego rodaka.",
                            NumberOfViews = 41L,
                            Subject = "Dawid Kubacki zajął 3 miejsce w konkursie!"
                        },
                        new
                        {
                            Id = 3L,
                            ArticleCategoryRefId = 4L,
                            ArticleModificationDate = "30.10.2019 12:24:44",
                            Content = "Olga Tokarczuk została tegoroczną laureatką Literackiej Nagrody Nobla za 2018 rok. W żadnej z innych kategorii nie odnosimy tak spektakularnych sukcesów. W jaki sposób przekonała opinię publiczną do swojego sukcesu. Co spowodowało, że Polska literatura zaczęła być uznawana na całym świecie? Czy rzeczywiście jesteśmy w ścisłej czołówce na świecie? Ostatni raz nagroda Nobla została przyznana innej polskiej pisarce, Wisławie Szymborskiej w 1996 roku. To naprawdę wielki sukces z którego powinniśmy być dumni",
                            NumberOfViews = 108L,
                            Subject = "Nobel dla Polki"
                        },
                        new
                        {
                            Id = 4L,
                            ArticleCategoryRefId = 5L,
                            ArticleModificationDate = "15.05.2019 10:21:09",
                            Content = "Co sądzą ludzie o czarnych dziurach? Czy istnieją naprawdę? Czy powinniśmy się ich obawiać? To pytanie nurtuje nas od wielu lat. Czarne dziury kojarzą się głównie ze śmiercią gwiazd. Jest to bardzo oczywiste stwierdzenie. Powstają w sposób naturalny, będąc końcowym efektem ewolucji największych gwiazd. Posiadają masę co najmniej kilku naszych Słońc. Gdy gwiazda zaczyna umierać, procesy termojądrowe z jego wnętrza przestają równoważyć nacisk z zewnątrz. Grawitacja zwycięża. Wkrótce więcej informacji.",
                            NumberOfViews = 101L,
                            Subject = "Czarne dziury istnieją naprawdę!"
                        },
                        new
                        {
                            Id = 5L,
                            ArticleCategoryRefId = 3L,
                            ArticleModificationDate = "28.02.2019 21:59:38",
                            Content = "Całkowita sprzedaż norweskiego gazu wyniosła ok 11 mld euro. Czarne złoto stanowi większość przychodów państwa położonego na Półwyspie Skandynawskim. Są też pomówienia, że tej ropy może kiedyś zabraknąć nowerskiemu przemysłowi.",
                            NumberOfViews = 38L,
                            Subject = "Norwegia wydobywa coraz wiecęj ropy."
                        },
                        new
                        {
                            Id = 6L,
                            ArticleCategoryRefId = 2L,
                            ArticleModificationDate = "28.12.2019 09:55:27",
                            Content = "Mózg jest uznawany za najważniejszy z ludzkich organów. Pełni wiele skomplikowanych funkcji. Wyróżnia się trzy części mózgowia. Jest to mózg właściwy, międzymózgowie oraz pień mózgu. Każda z tych części odróżnia się budową i pełnioną funkcją.",
                            NumberOfViews = 94L,
                            Subject = "Mózg człowieka"
                        },
                        new
                        {
                            Id = 7L,
                            ArticleCategoryRefId = 1L,
                            ArticleModificationDate = "29.12.2019 22:27:01",
                            Content = "Robert Lewandowski po raz czwarty w karierze został królem strzelców Bundesligi! Więcej razy po tą nagrodę sięgał tylko Gerd Muller. To bardzo niezwykłe. Wcześniej tego nie dokonał żaden z polskich napastników.",
                            NumberOfViews = 41L,
                            Subject = "Robert Lewandowski królem strzelców Bundesligi!"
                        },
                        new
                        {
                            Id = 8L,
                            ArticleCategoryRefId = 4L,
                            ArticleModificationDate = "29.12.2019 22:27:01",
                            Content = "Od kilku tygodni możemy cieszyć się pięknym latem w Kołobrzegu. Nie może dziwić fakt, że wiele osób wybrało w tym roku Bałtyk i piękny krajobraz miasta Kołobrzeg. Panują temperatury od 28 stopni Celsjusza. Taka temperatura powinna się utrzymać przez długie tygodnie tego pięknego lata.",
                            NumberOfViews = 76L,
                            Subject = "W Kołobrzegu piękna pogoda od soboty"
                        },
                        new
                        {
                            Id = 9L,
                            ArticleCategoryRefId = 5L,
                            ArticleModificationDate = "10.12.2019 07:43:22",
                            Content = "Dzisiaj ludzie nie mogą sobie wyobrazić życia bez elektryczności. Wszystko co nas otacza, komputery, radio, sprzęty domowego użytku. To wszystko opiera się o energię pochodzącą z elektryczności. W 1600 roku naukowiec William Gilbert jako pierwszy wytworzył iskrę elektryczną poprzez pocieranie bursztynu.",
                            NumberOfViews = 34L,
                            Subject = "Kto wynalazł elektryczność?"
                        },
                        new
                        {
                            Id = 10L,
                            ArticleCategoryRefId = 3L,
                            ArticleModificationDate = "10.11.2019 15:22:26",
                            Content = "Chińczycy zbudowali w rekordowym tempie kolejny lotniskowiec. Zajęło im to dosłownie dwa miesiące, podczas gdy amerykanie budują go w przeciągu dwóch lat. Taka sytuacja powoduje, że USA nie jest już największą potęgą militarną na świecie.",
                            NumberOfViews = 85L,
                            Subject = "Chińczycy budują nowy lotniskowiec"
                        });
                });

            modelBuilder.Entity("SpeechRecognitionThesis.Models.DatabaseModels.ArticleCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ArticleCategory");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Nauka"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Świat"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Kraj"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Popularnonaukowe"
                        });
                });

            modelBuilder.Entity("SpeechRecognitionThesis.Models.DatabaseModels.UserArticles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ArticleRefId");

                    b.Property<long>("UserRefId");

                    b.HasKey("Id");

                    b.HasIndex("ArticleRefId");

                    b.HasIndex("UserRefId");

                    b.ToTable("UserArticles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ArticleRefId = 1L,
                            UserRefId = 4L
                        },
                        new
                        {
                            Id = 2L,
                            ArticleRefId = 2L,
                            UserRefId = 3L
                        },
                        new
                        {
                            Id = 3L,
                            ArticleRefId = 3L,
                            UserRefId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            ArticleRefId = 4L,
                            UserRefId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            ArticleRefId = 5L,
                            UserRefId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            ArticleRefId = 6L,
                            UserRefId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            ArticleRefId = 7L,
                            UserRefId = 4L
                        },
                        new
                        {
                            Id = 8L,
                            ArticleRefId = 8L,
                            UserRefId = 4L
                        },
                        new
                        {
                            Id = 9L,
                            ArticleRefId = 9L,
                            UserRefId = 2L
                        },
                        new
                        {
                            Id = 10L,
                            ArticleRefId = 10L,
                            UserRefId = 3L
                        });
                });

            modelBuilder.Entity("SpeechRecognitionThesis.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvatarId");

                    b.Property<string>("CreateAccountDate")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("LastLoggedAccountDate")
                        .HasMaxLength(50);

                    b.Property<string>("LastUpdateAccountDate")
                        .HasMaxLength(50);

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AvatarId = 1,
                            CreateAccountDate = "30.05.2019 00:00:00",
                            Email = "guest@speechrecognition.com",
                            LastLoggedAccountDate = "24.08.2019 00:00:00",
                            LastUpdateAccountDate = "20.06.2019 00:00:00",
                            NickName = "Guest",
                            Password = "cc5ec2b61fbbdd18d85dd14ab60db397b21b5548999a6afd3ce9557b19c300494a5fd29987e03a6f06677c209b88de47684388de8250671cdd778799eecd018a"
                        },
                        new
                        {
                            Id = 2L,
                            AvatarId = 2,
                            CreateAccountDate = "22.04.2018 00:00:00",
                            Email = "robert@gmail.com",
                            LastLoggedAccountDate = "12.09.2019 00:00:00",
                            LastUpdateAccountDate = "21.02.2019 00:00:00",
                            NickName = "robert1234",
                            Password = "907be532d318507e73c44a7899eb7c81f97294ec5619c0e47d59f0d32f986ba87e42f51be6a461d42c5bfede284342afd735682b3b7926fd4c6ba69da9839a04"
                        },
                        new
                        {
                            Id = 3L,
                            AvatarId = 5,
                            CreateAccountDate = "20.01.2019 00:00:00",
                            Email = "michal854@example.com",
                            LastLoggedAccountDate = "28.06.2019 00:00:00",
                            LastUpdateAccountDate = "23.06.2019 00:00:00",
                            NickName = "michal854",
                            Password = "339136aa80c4abdd548dc4b9e9092992b5c40d0b6374fce880a4ceb74db580c741ffe0f64ac9081d6790b1715f7977eaa47d77eefd99c277354dbacee498bf2b"
                        },
                        new
                        {
                            Id = 4L,
                            AvatarId = 7,
                            CreateAccountDate = "30.04.2019 00:00:00",
                            Email = "witek@gmail.com",
                            LastLoggedAccountDate = "28.12.2019 00:00:00",
                            LastUpdateAccountDate = "21.12.2019 00:00:00",
                            NickName = "witek754",
                            Password = "120672f4755d88105e7653aa6e9d3792146921e387064e11761f283910ab6cfc25918d70d24df82f23b400ec1904f6d6f004132fb1cc49063f0b1acb72be2bdf"
                        },
                        new
                        {
                            Id = 5L,
                            AvatarId = 3,
                            CreateAccountDate = "29.03.2018 00:00:00",
                            Email = "adam243567@gmail.com",
                            LastLoggedAccountDate = "10.12.2019 00:00:00",
                            LastUpdateAccountDate = "04.10.2019 00:00:00",
                            NickName = "adam5",
                            Password = "dc092fd8666fab2589db452d95294c67d7928e261a56f968d20f1ce2365c76c1590094e1287c921418f072c26cc6e6c392d8175b96d824de432874b9f4ea46a6"
                        });
                });

            modelBuilder.Entity("SpeechRecognitionThesis.Models.Article", b =>
                {
                    b.HasOne("SpeechRecognitionThesis.Models.DatabaseModels.ArticleCategory", "ArticleCategory")
                        .WithMany()
                        .HasForeignKey("ArticleCategoryRefId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SpeechRecognitionThesis.Models.DatabaseModels.UserArticles", b =>
                {
                    b.HasOne("SpeechRecognitionThesis.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleRefId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SpeechRecognitionThesis.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserRefId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
